<a href="https://colab.research.google.com/github/Muhammad-Salman-Hassan/DeepLearning/blob/main/Filters_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Filters in CNN

One of the main components of CNNs are filters, which are square 
matrices that have dimensions nK × nK, where nK is an integer and is usually 
a small number, like 3 or 5. Sometimes filters are also called kernels.May be you can use photoshop for bluring the image sharpening the image and many opereation these are done by kernals or filters

In [2]:
import numpy as np


**The following kernel will allow the detection of 
horizontal edges**

In [5]:

arr=[[1,1,1],[0,0,0],[-1,-1,-1]]


[[1, 1, 1], [0, 0, 0], [-1, -1, -1]]

In [12]:
Hor_edge=np.array(arr)
Hor_edge

array([[ 1,  0, -1],
       [ 1,  0, -1],
       [ 1,  0, -1]])

**The following kernel will allow the detection of vertical 
edges**

In [9]:

arr_ver=[[1,0,-1],[1,0,-1],[1,0,-1]]


In [10]:
Ver_edge=np.array(arr_ver)
Ver_edge

array([[ 1,  0, -1],
       [ 1,  0, -1],
       [ 1,  0, -1]])

**The following kernel will allow the detection of edges 
when luminosity changes drastically**

In [14]:

arr_lum=[[-1,-1,-1],[-1,8,-1],[-1,-1,-1]]


In [15]:
Ver_edge=np.array(arr_lum)
Ver_edge

array([[-1, -1, -1],
       [-1,  8, -1],
       [-1, -1, -1]])

In [ ]:
'''
Note all above kernal have 3 by 3 shape mean we have 3 rows and 3 columns
'''